# if some value in not relevant for specific DBMS then use None


# [oracleSQL, postgreSQL]
# case-insensitive
dbms_type: oracleSQL

# relative path (to the main.py script) ot the input xlsx file
xlsx_location: test.xlsx

# in OracleSQL 'True' will keep SCN tracking on each row, instead of on whole table (default).
rowdependencies: False test

